version: '2'
services:
  vlo_data:
    image: registry.gitlab.com/clarin-eric/docker-alpine-nginx:1.0.5
    environment:
      - SOLR_DATA_HOME
    ports:
      - 8184:80
    volumes:
      - ${METADATA_VOLUME}:/srv/www-static/data:ro
      - ${RESULTSETS_VOLUME}:/srv/www-static/resultsets:ro
      - ${SITEMAP_VOLUME}:/srv/www-static/sitemap:ro
      - ./data/nginx-config/default.conf:/nginx_conf.d/default.conf:ro
      - vlo_www_data:/var/www/
    restart: unless-stopped
    networks:
        - network_vlo
volumes:
    vlo_www_data:
        external: false
