version: '2'
services:
  vlo-solr:
    ports:
      - 8983:8983
  vlo-web:
    environment:
      - VLO_MAPPING_DEFINITIONS_DIST_URL=https://github.com/clarin-eric/VLO-mapping/archive/development.tar.gz
      - VLO_DOCKER_PUBLIC_HOME_URL=https://localhost:8080
      - VLO_DOCKER_DATAROOTS_FILE=dataroots-testvm.xml
      - VLO_DOCKER_FILE_PROCESSING_THREADS=-1
      - VLO_DOCKER_SOLR_THREADS=2
      - VLO_DOCKER_DELETE_ALL_FIRST=false
      - VLO_DOCKER_MAX_DAYS_IN_SOLR=7
      - STATSD_PREFIX=vlo.test
      - VLO_DOCKER_WICKET_CONFIGURATION=development

