version: '2'
services:
  vlo_solr:
    image: registry.gitlab.com/clarin-eric/docker-solr:1.1.0
    environment:
      - SOLR_DATA_HOME
    depends_on:
      - vlo_solr_init # to ensure Solr home directory content
    entrypoint: ["bash", "-c", "[ -f ${SOLR_HOME_PROVISIONING_PATH}/solr.xml ]
                        && /usr/bin/entrypoint.sh"]
    volumes:
      - solr-home-provisioning:${SOLR_HOME_PROVISIONING_PATH}
      - vlo-solr-data:${SOLR_DATA_HOME}
    restart: on-failure
    networks:
        - network_vlo
  vlo_web:
    image: &vlo_web_image registry.gitlab.com/clarin-eric/docker-vlo-beta:1.5.0
    environment:
      - VLO_DOCKER_SOLR_URL=http://vlo_solr:8983/solr/vlo-index/
      - VLO_DOCKER_PUBLIC_HOME_URL=http://localhost:8080
      - VLO_DOCKER_PIWIK_ENABLE_TRACKER=false
      - VLO_DOCKER_WICKET_CONFIGURATION=deployment
    ports:
      - 8181:8080
    restart: on-failure
    networks:
        - network_vlo
  vlo_solr_init:
    image: *vlo_web_image
    entrypoint: ["sleep", "1"]
    user: solr
    volumes:
      # this copies data for Solr home directory provisioning
      - solr-home-provisioning:/opt/vlo/solr/vlo-solr-home
    restart: "no"
volumes:
    solr-home-provisioning:
        external: false
    vlo-solr-data:
        external: false
networks:
  network_vlo:
