version: '2'
services:
  vlo-solr:
    image: registry.gitlab.com/clarin-eric/docker-solr:solr7.4-1.0.0
    environment:
      - SOLR_HEAP
      - SOLR_DATA_HOME
      - SOLR_HOME_PROVISIONING_PATH
      - VLO_DOCKER_SOLR_USER_READ_ONLY
      - VLO_DOCKER_SOLR_PASSWORD_READ_ONLY
      - VLO_DOCKER_SOLR_USER_READ_WRITE
      - VLO_DOCKER_SOLR_PASSWORD_READ_WRITE
      - VLO_DOCKER_SOLR_PASSWORD_ADMIN
    depends_on:
      - vlo-solr-init # to ensure Solr home directory content
    entrypoint: ["bash", "-c", "[ -f ${SOLR_HOME_PROVISIONING_PATH}/solr.xml ]
                        && /opt/solr-init/filter-solr-security.sh
                        && /usr/bin/entrypoint.sh"]
    volumes:
      - solr-home-provisioning:${SOLR_HOME_PROVISIONING_PATH}
      - vlo-solr-data:${SOLR_DATA_HOME}
      - ./solr-init:/opt/solr-init
    restart: on-failure
    networks:
        - network_vlo
  vlo-web:
    image: &vlo_web_image registry.gitlab.com/clarin-eric/docker-vlo-beta:1.6.3
    environment:
      - VLO_DOCKER_SOLR_URL=http://vlo-solr:8983/solr/vlo-index/
      ## from .env
      - VLO_MAPPING_DEFINITIONS_DIST_URL
      - VLO_DOCKER_PUBLIC_HOME_URL
      - VLO_DOCKER_FILE_PROCESSING_THREADS
      - VLO_DOCKER_SOLR_THREADS
      - VLO_DOCKER_DELETE_ALL_FIRST
      - VLO_DOCKER_MAX_DAYS_IN_SOLR
      - VLO_DOCKER_VCR_MAXIMUM_ITEMS_COUNT

      - VLO_DOCKER_TOMCAT_JAVA_OPTS
      - VLO_DOCKER_IMPORTER_JAVA_OPTS

      - VLO_DOCKER_WICKET_CONFIGURATION
      - VLO_DOCKER_DATAROOTS_FILE

      - VLO_DOCKER_CONCEPT_REGISTRY_URL
      - VLO_DOCKER_VOCABULARY_REGISTRY_URL
      - VLO_DOCKER_FEEDBACK_FORM_URL
      - VLO_DOCKER_FCS_BASE_URL
      - VLO_DOCKER_LRS_BASE_URL
      - VLO_DOCKER_VCR_SUBMIT_ENDPOINT
      
      - VLO_DOCKER_SOLR_USER_READ_ONLY
      - VLO_DOCKER_SOLR_PASSWORD_READ_ONLY
      - VLO_DOCKER_SOLR_USER_READ_WRITE
      - VLO_DOCKER_SOLR_PASSWORD_READ_WRITE
      - VLO_DOCKER_SOLR_PASSWORD_ADMIN
      
      - VLO_DOCKER_PIWIK_ENABLE_TRACKER
      - VLO_DOCKER_PIWIK_SITE_ID
      - VLO_DOCKER_PIWIK_HOST
      - VLO_DOCKER_PIWIK_DOMAINS
      
      - VLO_DOCKER_STATSD_HOST
      - VLO_DOCKER_STATSD_PORT
      - STATSD_PREFIX
    volumes:
      - ${METADATA_VOLUME}:${METADATA_DIR}
      - ${SITEMAP_VOLUME}:/opt/sitemap
      - ${STATSD_VOLUME}:/opt/statsd
    restart: on-failure
    networks:
        - network_vlo
  vlo-solr-init:
    image: *vlo_web_image
    entrypoint: ["sleep", "1"]
    volumes:
      # this copies data for Solr home directory provisioning
      - solr-home-provisioning:/opt/vlo/solr/vlo-solr-home
    restart: "no"
    networks:
        - network_vlo
volumes:
    solr-home-provisioning:
        external: false
    vlo-solr-data:
        external: false
    vlo-statsd:
        external: false
    vlo-sitemap:
        external: false
    vlo-data: 
        external: false
    vlo-resultsets:
        external: false
networks:
  network_vlo:
