version: '2'
services:
  vlo_solr_init:
    image: registry.gitlab.com/clarin-eric/docker-vlo-beta:${VLO_IMAGE_VERSION}
    entrypoint: /opt/populate-vlo-solr-home.sh
    environment:
      - SOLR_HOME
    volumes:
      - vlo-solr-home:${SOLR_HOME}
    restart: "no"
  vlo_solr:
    image: registry.gitlab.com/clarin-eric/docker-solr:${SOLR_IMAGE_VERSION}
    environment:
      - SOLR_HOME
      - SOLR_DATA_HOME
    depends_on:
      - vlo_solr_init
    entrypoint: ["/bin/bash", 
                    "-c", 
                    "while [ ! -f ${SOLR_HOME}/solr.xml ];
                    do
                        echo 'Waiting for Solr home content...'; 
                        sleep 1; 
                    done
                        && chown -R solr ${SOLR_DATA_HOME}
                        && /usr/bin/entrypoint.sh"]
    ports:
      - 8983:8983
    volumes:
      - vlo-solr-home:${SOLR_HOME}
      - ${HOST_SOLR_DATA_HOME}:${SOLR_DATA_HOME}
    restart: unless-stopped
  vlo_web:
    image: registry.gitlab.com/clarin-eric/docker-vlo-beta:${VLO_IMAGE_VERSION}
    environment:
      - VLO_DOCKER_SOLR_URL=http://vlo_solr:8983/solr/vlo-index/
      - VLO_DOCKER_PUBLIC_HOME_URL
    depends_on:
      - vlo_solr
    ports:
      - 8080:8080
    links:
      - vlo_solr
    restart: unless-stopped
volumes:
    vlo-solr-home:
        external: false
