version: '2'
services:
  vlo_solr_init:
    image: registry.gitlab.com/clarin-eric/docker-vlo-beta:${VLO_IMAGE_VERSION}
    entrypoint: ["sleep", "1"]
    volumes:
      # this initialises the Solr home directory
      - vlo-solr-home:/opt/vlo/solr/vlo-solr-home
    restart: "no"
  vlo_solr:
    image: registry.gitlab.com/clarin-eric/docker-solr:${SOLR_IMAGE_VERSION}
    environment:
      - SOLR_HOME
      - SOLR_DATA_HOME
    depends_on:
      - vlo_solr_init # to ensure Solr home directory content
    entrypoint: ["bash", "-c", "[ -f ${SOLR_HOME}/solr.xml ] && /usr/bin/entrypoint.sh"]
    volumes:
      - vlo-solr-home:${SOLR_HOME}
      - ${HOST_SOLR_DATA_HOME}:${SOLR_DATA_HOME}
    restart: unless-stopped
  vlo_web:
    image: registry.gitlab.com/clarin-eric/docker-vlo-beta:${VLO_IMAGE_VERSION}
    environment:
      - VLO_DOCKER_SOLR_URL=http://vlo_solr:8983/solr/vlo-index/
      - VLO_DOCKER_PUBLIC_HOME_URL
    links:
      - vlo_solr
    ports:
      - 8080:8080
    restart: unless-stopped
volumes:
    vlo-solr-home:
        external: false
