version: '2'
services:
  exposure-frontend:
    image: docker-vlo-exposure-frontend:d9dfd08
    environment:
      - VLO_DOCKER_EXPOSURE_DB_NAME=vlo_exposure
      - VLO_DOCKER_EXPOSURE_DB_USER=vlo_exposure
      - VLO_DOCKER_EXPOSURE_DB_HOST=exposure-db
      - VLO_DOCKER_EXPOSURE_DB_PORT=5432
      - VLO_DOCKER_EXPOSURE_DB_PASSWORD
    networks:
        - network_vlo


