version: '2'
services:
  vlo-web:
    environment:
      - VLO_DOCKER_EXPOSURE_ENABLED=true
      - VLO_DOCKER_EXPOSURE_DB_NAME=vlo_exposure
      - VLO_DOCKER_EXPOSURE_DB_USER=vlo_exposure
      - VLO_DOCKER_EXPOSURE_DB_HOST=exposure-db
      - VLO_DOCKER_EXPOSURE_DB_PORT=5432
      - VLO_DOCKER_EXPOSURE_DB_PASSWORD
  exposure-db:
    image: registry.gitlab.com/clarin-eric/docker-postgres:1.0.2
    restart: always
    environment:
      - "POSTGRES_DB=vlo_exposure"
      - "POSTGRES_USER=vlo_exposure"
      - "POSTGRES_PASSWORD=${VLO_DOCKER_EXPOSURE_DB_PASSWORD}"
    volumes:
      - exposure_pg_data:/var/lib/postgresql/data:rw
      - ./exposure/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - network_vlo
    expose:
      - 5432
volumes:
    exposure_pg_data:
        external: false
