version: '2'
services:
  exposure-frontend:
    image: registry.gitlab.com/clarin-eric/docker-vlo-exposure-frontend:1.0.0-alpha1
    environment:
      - VLO_DOCKER_EXPOSURE_DB_NAME=vlo_exposure
      - VLO_DOCKER_EXPOSURE_DB_USER=vlo_exposure
      - VLO_DOCKER_EXPOSURE_DB_HOST=exposure-db
      - VLO_DOCKER_EXPOSURE_DB_PORT=5432
      - VLO_DOCKER_EXPOSURE_DB_PASSWORD
    networks:
        - network_vlo


