# Configuration overlay for monitoring with jmxtrans and statsd
#
# In order to use, you will need to export the 
# JMXTRANS_HOST_ALIAS, JMXTRANS_STATSD_HOST and JMXTRANS_STATSD_PORT variables!

version: '2'
services:
  vlo-solr:
    environment:
      - ENABLE_REMOTE_JMX_OPTS=true
      - RMI_PORT=18983
      - SOLR_OPTS=-Djava.rmi.server.hostname=vlo-solr
    networks:
      - network_vlo
  jmxtrans:
    image: registry.gitlab.com/clarin-eric/docker-jmxtrans:1.1.2
    depends_on:
      - vlo-solr
    environment:
      - JSON_DIR=/var/lib/jmxtrans
      - JMXTRANS_OPTS=-Dhost_alias=${JMXTRANS_HOST_ALIAS} -Dstatsd_host=${JMXTRANS_STATSD_HOST} -Dstatsd_port=${JMXTRANS_STATSD_PORT} -Dsolr_jmx_host=vlo-solr -Dsolr_jmx_port=18983 
      - SOLR_HOST=vlo-solr
      - SOLR_PORT=8983
    volumes:
      - ./jmxtrans:/var/lib/jmxtrans
      - ./jmxtrans/wait-for-solr.sh:/init/wait-for-solr.sh
      #- ./jmxtrans/custom-log4j.xml:/usr/share/jmxtrans/conf/log4j.xml
    networks:
      - network_vlo
      - network_internet
