version: '2'
services:
  vlo-web:
    environment:
      #- VLO_DOCKER_LINK_CHECKER_MONGO_DB_NAME=${VLO_LINK_CHECKER_MONGO_DB_NAME}
      #- VLO_DOCKER_LINK_CHECKER_MONGO_DB_CONNECTION_STRING=mongodb://vlo-linkchecker-mongo:27017
      - VLO_DOCKER_LINK_CHECKER_DB_CONNECTION_STRING=jdbc:mysql://vlo-linkchecker-db:3306/linkchecker
      - VLO_DOCKER_LINK_CHECKER_DB_USER=linkchecker
      - VLO_DOCKER_LINK_CHECKER_DB_PASSWORD=linkchecker
  vlo-linkchecker-db:
    image: registry.gitlab.com/clarin-eric/docker-mariadb:1.0.19
    environment:
      - MYSQL_ROOT_PASSWORD=${VLO_LINK_CHECKER_DB_ROOT_PASSWD}
      - MYSQL_DATABASE=linkchecker
      - MYSQL_PASSWORD=linkchecker
    volumes:
      - linkckecker_mariadb_data:/var/lib/mysql
      - ${VLO_LINK_CHECKER_DB_DUMP_HOST_DIR}:/docker-entrypoint-initdb.d
      #- ${VLO_LINK_CHECKER_MONGO_DUMP_HOST_DIR}:${VLO_LINK_CHECKER_MONGO_DUMP_CONTAINER_DIR}
    restart: unless-stopped
    expose:
      - "3306"
    networks:
        - network_vlo
volumes:
    linkckecker_mariadb_data:
        external: false
