version: '2.4'
services:
  vlo-web:
    environment:
      - TOMCAT_PROXY_REMOTE_IP_HEADER=${TOMCAT_PROXY_REMOTE_IP_HEADER:-x-forwarded-for}
      - TOMCAT_PROXY_INTERNAL_PROXIES=${TOMCAT_PROXY_INTERNAL_PROXIES:-.\*}
      - TOMCAT_PROXY_PROXIES_HEADER=${TOMCAT_PROXY_PROXIES_HEADER:-x-forwarded-by}
      - TOMCAT_PROXY_PROTOCOL_HEADER=${TOMCAT_PROXY_PROTOCOL_HEADER:-x-forwarded-proto}
      - TOMCAT_PROXY_HTTP_SERVER_PORT={TOMCAT_PROXY_HTTP_SERVER_PORT:-80}
      - TOMCAT_PROXY_HTTPS_SERVER_PORT={TOMCAT_PROXY_HTTPS_SERVER_PORT:-443}
    volumes:
      # override server conf to support proxy
      - ./tomcat/init/tomcat-vlo-init.sh:/init/tomcat-vlo-init.sh
      - ./tomcat/conf/server.xml:/srv/tomcat8/conf/server.template.xml:ro
  vlo-proxy:
    image: registry.gitlab.com/clarin-eric/docker-alpine-nginx:2.2.0
    environment:
      - SOLR_DATA_HOME
    ports:
      - ${NGINX_PROXY_HTTPS_PORT:-8143}:443
    volumes:
      - ./nginx/proxy-init.sh:/init/vlo-proxy-init.sh
      - ${METADATA_VOLUME:-vlo-data}:/srv/www-static/data:ro
      - ${RESULTSETS_VOLUME:-vlo-resultsets}:/srv/www-static/resultsets:ro
      - ${SITEMAP_VOLUME:-vlo-sitemap}:/srv/www-static/sitemap:ro
      - ./nginx/http.d/default.conf:/etc/nginx/http.d/default.conf:ro
      - ./nginx/http.d/inc/vlo.inc:/etc/nginx/http.d/inc/vlo.inc:ro
      - ./nginx/mime.types:/etc/nginx/extra_mime.types:ro
      - ${WEB_STATIC_DATA_VOLUME:-vlo_www_data}:/srv/www-static/root:ro
      - ${PROXY_VLO_CONFIG_HTPASSWD_FILE:-../../vlo-config-htpasswd}:/etc/nginx/vlo-config-htpasswd
    tmpfs:
      - /var/cache/nginx-vlo
    restart: unless-stopped
    networks:
        - network_vlo
        - network_internet
volumes:
    vlo_www_data:
        external: false
    vlo_nginx_cache:
        
