version: '2'
services:
  vlo-web:
    environment:
      - TOMCAT_PROXY_REMOTE_IP_HEADER
      - TOMCAT_PROXY_INTERNAL_PROXIES
      - TOMCAT_PROXY_PROXIES_HEADER
      - TOMCAT_PROXY_PROTOCOL_HEADER
      - TOMCAT_PROXY_HTTP_SERVER_PORT
      - TOMCAT_PROXY_HTTPS_SERVER_PORT
    volumes:
      # override server conf to support proxy
      - ./tomcat/init/tomcat-vlo-init.sh:/init/tomcat-vlo-init.sh
      - ./tomcat/conf/server.xml:/srv/tomcat8/conf/server.template.xml:ro
  vlo-proxy:
    image: registry.gitlab.com/clarin-eric/docker-alpine-nginx:2.0.10
    environment:
      - SOLR_DATA_HOME
    ports:
      - ${NGINX_PROXY_HTTP_PORT}:81
      - ${NGINX_PROXY_HTTPS_PORT}:443
    volumes:
      - ./nginx/proxy-init.sh:/init/vlo-proxy-init.sh
      - ${METADATA_VOLUME}:/srv/www-static/data:ro
      - ${RESULTSETS_VOLUME}:/srv/www-static/resultsets:ro
      - ${SITEMAP_VOLUME}:/srv/www-static/sitemap:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/conf.d/inc/vlo.inc:/etc/nginx/conf.d/inc/vlo.inc:ro
      - ./nginx/conf.d/mime.types:/etc/nginx/extra_mime.types:ro
      - ${WEB_STATIC_DATA_VOLUME}:/srv/www-static/root:ro
      - ${PROXY_VLO_CONFIG_HTPASSWD_FILE}:/etc/nginx/vlo-config-htpasswd
    tmpfs:
      - /var/cache/nginx-vlo
    restart: unless-stopped
    networks:
        - network_vlo
        - network_internet
volumes:
    vlo_www_data:
        external: false
    vlo_nginx_cache:
        
