# VLO docker compose configuration overlay for production (and beta)
version: '2'
services:
  vlo_solr:
    environment:
      - SOLR_JAVA_MEM=-Xms1G -Xmx8G
    volumes:
      - solr_temp:/tmp
  vlo_web:
    environment:
      - VLO_MAPPING_DEFINITIONS_DIST_URL=https://github.com/clarin-eric/VLO-mapping/archive/master.tar.gz
      - VLO_DOCKER_PUBLIC_HOME_URL=https://vlo.clarin.eu
      - VLO_DOCKER_DATAROOTS_FILE=dataroots-production.xml
      - VLO_DOCKER_FILE_PROCESSING_THREADS=-1
      - VLO_DOCKER_SOLR_THREADS=4
      - VLO_DOCKER_DELETE_ALL_FIRST=false
      - VLO_DOCKER_MAX_DAYS_IN_SOLR=7
      - VLO_DOCKER_PIWIK_ENABLE_TRACKER=true
      - VLO_DOCKER_PIWIK_SITE_ID=3
      - VLO_DOCKER_PIWIK_HOST=https://stats.clarin.eu/
      - VLO_DOCKER_PIWIK_DOMAINS=*.vlo.clarin.eu
      - VLO_DOCKER_STATSD_HOST
      - VLO_DOCKER_STATSD_PORT
      - STATSD_PREFIX
      - VLO_DOCKER_WICKET_CONFIGURATION=deployment
    volumes:
      - ${METADATA_VOLUME}:${METADATA_DIR}
      - ${SITEMAP_VOLUME}:/opt/sitemap
      - ${STATSD_VOLUME}:/opt/statsd
volumes:
  solr_temp:
    external: false
